# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-11-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JURISDICTION_NAME', models.CharField(max_length=255)),
                ('COUNT_FEMALE', models.CharField(max_length=255)),
                ('COUNT_MALE', models.CharField(max_length=255)),
            ],
        ),
    ]
